double rayscat();
double rayscatHG();
double taufmp();
double sfcrefl();
double randphi();
double cross(double *u, double *v, double *w);
int checkorth(double *u, double *v);
void printvec(double *v, int len);
void norm(double *v, int len);
int checkangle(double *u, double *v, int len,double mu);
double givelen(double *v, int len);
double randnum();
void scattering_ray(double *pos_i, double *dir_i, double *dir_f);
